### ISSUE TITLE
Basic howto

### ISSUE THREAD

**Issue by cinterloper** [luapower/low#1]
Is there a simple description of how to get started with the luapower terra libs?

**Comment by capr** [comment]
I don't spend much time on docs these days because my perception is that there's not enough demand for Terra right now. I barely see any demand for LuaJIT anymore (I'm talking open-source). Not that I care much about that as far as my own purposes go, but for writing docs (which I don't need obviously), there has to be an incentive. 

But there's a deeper reason too, for this module in particular because this module is sort of a bootstrap/language-extension module containing various idioms, meta-programming patterns, stdlib wrappers etc. (like [glue](http://luapower.com/glue) is for Lua) which were arrived at organically from the process of developing _other things_, so it would be hard to understand this API from its functional documentation alone (if that were to exist) because you wouldn't know _why_ and _where_ to apply these idioms/patterns, so the docs would have to include a lot of _insightful_ examples and justifications as well which is quite time-consuming. 

So lacking docs, the next best thing (actually the better thing IMO but takes more effort) is to try and solve _an actual problem_ from scratch and when you feel that you might need some pattern or data structure but don't know its precise form yet, look into the luapower code and maybe you'll find that idea in a more developed/mature stage and you can use that.

**Comment by cinterloper** [comment]
Yes, thanks for the coaching but I was hoping the terra ecosystem had developed some reusable code. Guess its to much to hope for.

**Comment by capr** [comment]
This _is_ reusable code, but in order to reuse it you have to _read the code_. What you're asking for is black-box abstractions that don't leak details to you and you can use by documentation alone without looking at the code. That's fine, most people want just that. But this is not a good place to look for that, for a few reasons: 

* my code is in a state of flux, just look at the commits. I always find better ways to do things, and things take years to stabilize (it's not all that bad, there is a spectrum of stability there, but still). 

* metaprogramming is more of a thinking tool, and different people think differently (and thinking is a process, going back to my previous point). This code shows you how I think. If there's any value in it, it's more in the code and less in the APIs, but for that you have to _read the code_.

* the metaprogramming paradigm in general is not that good at providing that level of isolation that you're looking for and having that as a goal is not productive. This pursuit has failed before, see https://en.wikipedia.org/wiki/Extensible_programming#Death_of_the_historical_movement
